# -*- coding: utf-8 -*-
"""task7_sales_summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UQ0slRvfDPeu8efs9TgoDIUXIARJZ7G
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

cursor.execute("DELETE FROM sales")

sample_data = [
    ("Apple", 10, 5),
    ("Banana", 15, 3),
    ("Apple", 20, 5),
    ("Mango", 5, 8),
    ("Banana", 10, 3),
    ("Mango", 10, 8)
]

cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)
conn.commit()

query = """
SELECT
    product,
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

df = pd.read_sql_query(query, conn)

print("📊 Sales Summary:")
print(df)

df.plot(kind='bar', x='product', y='revenue', title='Revenue by Product', color='skyblue')
plt.ylabel("Revenue")
plt.tight_layout()
plt.savefig("sales_chart.png")
plt.show()

conn.close()

from google.colab import files
files.download("sales_data.db")